### ISSUE TITLE
Is it possible to hide/reset an active icon/image by a notification from another module?

### ISSUE THREAD

**Issue by lxne** [ralberth/MMM-ScriptScheduler#3]
Hi again,

I imagine this might come in handy for others, too.
Besides volume-control I am using ScriptScheduler to set scheduled pi shutdowns. Every time a shutdown is being set an icon shows up and you know that the raspberry Pi will shutdown soon. With gesture control I can cancel the shutdown "shutdown -c" but off course the icon stays visible. That's what's working so far.

Now what I would love is sending a notification to ScriptScheduler to hide the shutdown icon when canceling a shutdown. The sender in this case would be MMM-GroveGestures.
Three kinds of executions are available:
```
"GESTURE-SEQUENCE" : {
  shellExec: "...",
  notificationExec: { ... },
  moduleExec: { ... }
}
```
[Github repository of MMM-GroveGestures.](https://github.com/eouia/MMM-GroveGestures#structure-of-command-in-configuration)

Because I am controlling volume with gestures, too, I again would love to hide icons if I manually change the volume. Almost the same situation.

Is this in any way doable?

Best wishes!

**Comment by ralberth** [comment]
Wild idea, I like it!

MMM-ScriptScheduler doesn't support it today, but it's a simple change based on what I read about MMM-GroveGestures.

This thread is now a new feature request, congrats.  I'll create a new event that you can configure in GroveGestures so you can manually turn on or off any icons, or just turn them all off as options.  You'd configure GroveGestures something like this:

```javascript
"LEFT": {
    notificationExec: {
        notification: "SCRIPTSCHEDULER_ALL_OFF",
        payload: null
    }
},
```

or 

```javascript
"LEFT": {
    notificationExec: {
        notification: "SCRIPTSCHEDULER_SHOW_ICON",
        payload: { index: 3 }
    }
},
```

The former will turn off every icon/image in ScriptScheduler.  The latter will turn off everything and make sure only the icon/image in your configuration with offset 3 (counting from zero) is on.

This feature wouldn't trigger anything to actually be executed, just alter what is displayed on the screen.

Alternately, I could whip up a thing where sending  notification from GroveGestures would trigger an action in ScriptScheduler as if it's normal time had come.  This would (as a side effect) change the icon automatically too.

What do you think?

**Comment by lxne** [comment]
Great thoughts!

Being able to control the icons as you described would be awesome.

I think the alternate scenario resides more in the would-be-nice-to-have realm than really being needed. Because with `shellExec: "..."` commands can be triggered directly within GroveGestures and it's probably the same with other input modules.

**Comment by lxne** [comment]
Hi, I am just curious.
Did you have some time to look into this a bit more?

Best wishes,
Alex

**Comment by ralberth** [comment]
All set!  I just committed the support for SCRIPTSCHEDULER_ALL_OFF and SCRIPTSCHEDULER_SHOW_ICON.  Check out the README file for ScriptScheduler and have fun trying it out.  Let me know here if you have any problems.  

```bash
cd modules/MMM-ScriptScheduler
git pull
npm install
```

I'll leave this open a while longer so we can chat about any problems getting up and working.

**Comment by lxne** [comment]
Awesome! I hope I can test it tomorrow.
Thank you very much. This is great news.
Best wishes.

**Comment by lxne** [comment]
I love it.
Tested it and works great!

I tested the following within my GroveGesture configuration and it worked just fine:
```
        "RIGHT-LEFT": {
                notificationExec: {
                      notification: "SCRIPTSCHEDULER_SHOW_ICON",
                      payload: {
                                index: 1,
                                }
                },
        },
        "LEFT-RIGHT": {
                notificationExec: {
                      notification: "SCRIPTSCHEDULER_ALL_OFF",
                      payload: null,
                },
        },
```
On the [documentation page under Broadcast Notifications](https://github.com/ralberth/MMM-ScriptScheduler#broadcast-notifications) you use "SCRIPTSCHEDULER_ALL_OFF" in both examples. the second one should probably be "SCRIPTSCHEDULER_SHOW_ICON", right?

The only way to improve this significantly now, would be the possibility to have different slots for displaying more icons at once. But that's probably a huge and time consuming effort. Off course other modules could benefit greatly from that by using ScriptScheduler.
My had's just spinning now. If you do want to put more effort into this, it might actually be a good idea to split ScriptScheduler into two modules:
**ScriptScheduler**, which handles the scheduled scripts but no icons itself and maybe something like **Iconification**, for handling icon notifications. I think such a module would be very welcome amongst other module developers and the MagicMirror community.

I would love to help. But unfortunately my programming knowledge is very very basic. Helping with ideas, grafix and testing I could do.

Best wishes,
Alex

**Comment by ralberth** [comment]
Glad it works!  I just corrected the documentation...thanks for the pointer.

I took your neat idea and created [Issue #5](https://github.com/ralberth/MMM-ScriptScheduler/issues/5) so we can track it as a separate thought.  For now, it's a New Feature Request.  I'm not sure I like it, but you're a user and you suggested it, so it earns a separate ticket as evidence.  Maybe someone else will "+1" it and we can get some traction.

Since you have the new notifications running, let's close this as resolved.  If it fails, please re-open and we'll dig into it some more.

**Comment by lxne** [comment]
Thumbs up.
Thank you.
